### ISSUE TITLE
Общие правки

### ISSUE THREAD

**Issue by elemeNtk0** [Aquafresh/business#2]
- [ ] Если это _email_, то должен быть **mailto**:

``` html
<a class="email" href="#">info@business.com</a>
```
- [ ]  Думаю тут было бы неплохо сделать ссылки с падингом. Т.к. у тебя кнопка справа по высоте больше, а они на одном уровне.
  ![1](https://cloud.githubusercontent.com/assets/9047433/7660332/a5d7926c-fb51-11e4-82d7-7324167406c5.png)
- [ ] Инлайн блок. Без обнуления отступов — как-то «опасно» =) (P.s. бордер добавил, чтобы показать отступ)
  ![2](https://cloud.githubusercontent.com/assets/9047433/7660464/f3f3e1f2-fb52-11e4-9f01-07826d0cbb9a.png)
- [ ] А ты уверен, что паддинг для заголовка нужен, может лучше для блока-родителя? 

``` css
.section-title>h3 {
  padding-top: 102px;
}
```
- [ ] Строчный элемент делать блочным? может тогда просто оставить блочный элемент?

``` css
.section-title>span {
  display: block;
}
```
